### ISSUE TITLE
Delete a Relation between Nodes

### ISSUE THREAD

**Issue by code-inflation** [grafit-io/grafit#5]
**Description of problem**
There should be a way for a user to delete connections between a content-node and a concept-node.

**Solution**
Provide the possibility for the user to delete existing connections between content and generated or manually added nodes.
Add a small delete button is displayed on the concept.

**Additional context**

**Criteria for acceptance**
- [x] The user can delete unwanted connections between nodes

**Comment by disperate** [comment]
How can we prevent auto generated connections to reappear? Are all deleted connections persisted as some kind of blacklist for the concept node to content node mapping?

**Comment by code-inflation** [comment]
> How can we prevent auto generated connections to reappear? Are all deleted connections persisted as some kind of blacklist for the concept node to content node mapping?

On the relationship between the article nodes in neo4j there is now a property that represents if the relationship is hidden from the user. 
The conceptrunner does not override this property when the tf_idf values get updated.
